use_frameworks!

platform :ios, '15.0'

target 'Duxer_Example' do
  pod 'Duxer', :path => '../'

  pod 'Swild'
  pod 'WrapperCell'

  target 'Duxer_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
